# Generated by Django 2.2.1 on 2020-05-04 14:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_book_rating_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating_u',
            field=jsonfield.fields.JSONField(),
        ),
    ]
